- name: This is  playbook file is to install LEMP localhost
  hosts: localhost
  become: true
  connection: local
  tasks:
     - name: update apt
       apt:
        name: "*"
        state: latest

     - name: install nginx
       apt:
         name: nginx
         state: present

     - name: start nginx
       service:
         name: nginx
         state: started

     - name: install mysql
       apt:
        name: mariadb-server
        state: present
     
     - name: start mysql
       service: 
         name: mariadb
         state: started
      
     - name: install php
       apt:
        name: php
        state: present

     - name: install php-fpm 
       apt:
        name: php8.3-fpm
        state: present

     - name: start php-fpm
       service: 
        name: php8.3-fpm
        state: started

