$ANSIBLE_VAULT;1.1;AES256
37656238346233306639373865353139366266386564383465616433333763633335663035323333
6637353838633637633334326633373735393863363562390a623838313462623464303261663534
63656539313666313734363265653532346461646664633735366535353032393136336331323739
3965636164303138360a626364636663383937623733656666643939646261643364646663373732
66356431643138386665633435373537303131313132636561326630636366353531386462613836
36393562333635636332383331343137623635366634303865653136396365656431393264303133
38323032333334666631373732383836633236323538386261353437626365643162326332303839
33386165353639363231653830663030653665393764366565636433386233663065633864616532
33383562343763623263316230636562383066643736636436656639363637373262376163653861
35316530313563333932366663303263653062333536303164366262653162356434316431353139
64343433306663316238663937343062333735613762663363663833323062653432636531353261
66393235386265613037376234393337333064333632653831396333333530663637353034373635
65303562336461336233303733376564366535303438646636303732396630613136
