$ANSIBLE_VAULT;1.1;AES256
39656261623163383934386466643337353539613665306663613734373232343130383363383337
6135616130343831313138613230343539373937613039640a633131396637323361393063343934
64303164376331313233636166306163396132313036656334346166376334303939323866623934
6236326237646366300a343039646663306261653062643865306164356434613934333736656433
34623461363533303039383534633338613163333637376564363235343438626663343131316462
3130353537343432663535393662363138343832383265326437
